package com.fit2081.dailyapp.provider;

import static com.fit2081.dailyapp.provider.Task.TABLE_NAME;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * This class represents each to do item that will be shown in the recycler view
 */

@Entity(tableName = TABLE_NAME)
public class Task {
    public static final String TABLE_NAME = "tasks";
    public static final String COLUMN_ID = "taskId";
    public static final String COLUMN_TASK = "taskItem";

    @PrimaryKey(autoGenerate = true)
    @NonNull
    @ColumnInfo(name = COLUMN_ID)
    private int id;

    @ColumnInfo(name = COLUMN_TASK)
    private String task;

    public Task(String task) {
        this.task = task;
    }

    // setter for autogenerated id
    public void setId(@NonNull int id) {
        this.id = id;
    }

    // getter for id
    public int getId() {
        return id;
    }

    // getter for task

    public String getTask() {
        return task;
    }
}
